### ISSUE TITLE
getActivity() in CyborgControllerBase should return CyborgActivity

### ISSUE THREAD

**Issue by MatanKoby** [nu-art/cyborg-core#3]
Currently it returns Activity, although it always returns a CyborgActivity, or an inheritor of.

**Comment by TacB0sS** [comment]
DONE!

I was thinking about this for a while... I guess you are correct. I tried to keep it Activity in case I needed to extend another activity for a feature or something, but it is pointless... if your feature requires a specific activity, then two things: 

1. that service should be a shamed of themselves!
2. don't use it because they don't know what they are doing!

but if you must, just have another activity in your project.
